### ISSUE TITLE
No module named concurrent.futures

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/gremlin-python-tutorial#1]
./run -p
starting python test code
Traceback (most recent call last):
  File "gt1.py", line 2, in <module>
    from gremlin_python.driver.driver_remote_connection import DriverRemoteConnection
  File "/usr/local/lib/python2.7/dist-packages/gremlin_python/driver/driver_remote_connection.py", line 19, in <module>
    from concurrent.futures import Future
ImportError: No module named concurrent.futures

**Comment by spmallette** [comment]
i guess with python 2 you have to `pip install futures` . not sure why that doesn't get resolved with gremlinpython (but i'm not deeply knowledgeable with python so i'm not sure what's expected there for python devs).
